_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 30
                - 41
                - 49
                - 63
                - 80
            "2":
                - 1
                - 30
                - 41
                - 49
                - 63
                - 80
            "3":
                - 2
                - 14
                - 16
                - 55
            "4": 3.11.13
            "5": 0.20.1
            "10":
                - 20
            "12": 0.20.1
            "13": linux-x86_64
augmentations:
    value:
        Cutout:
            p: 0
        ElasticTransform:
            p: 0
        GaussianBlur:
            p: 0
            value:
                - 0.1
                - 2
        GaussianNoise:
            p: 0
        HorizontalFlip:
            p: 0.3
        MultNoise:
            p: 0
        RandomResizedCrop:
            interpolation: 1
            p: 0.3
            scale:
                - 0.2
                - 1
        RandomRotation:
            p: 0.6
        VerticalFlip:
            p: 0.3
dataloader:
    value:
        annotation_path: ../dataset/annotations.json
        atmospheric_channels:
            - total_column_water_vapour
            - surface_pressure
            - vertical_integral_of_temperature
        augment: true
        batch_size: 48
        geomorphology_channels:
            - insar_difference
            - insar_coherence
            - dem
        image_size: 512
        mask_target: union
        max_samples_per_shard: 128
        num_workers: 8
        persistent_workers: false
        prefetch_factor: 2
        seed: 42
        task: classification
        test_years:
            - "20200601"
            - "20211231"
        timeseries: false
        timeseries_data: ../dataset/quality_timeseries.json
        timeseries_length: 1
        train_years:
            - "20140101"
            - "20191231"
        val_years:
            - "20200101"
            - "20200531"
        webdataset: true
        webdataset_initial_buffer: 300
        webdataset_root: /scratch/SDF25/Imagery/Hephaestus_Minicubes_v0_webdataset/
        webdataset_shuffle_size: 100
        webdataset_write_processes: 8
        zarr_path: /scratch/SDF25/Imagery/Hephaestus_Minicubes_v0/
model:
    value:
        architecture: ViT
        mask_ratio: 0.6
        model: mae_vit_large_patch16
        norm_pix_loss: false
        ssl_method: mae
        stage: pretraining
train:
    value:
        blr: 0.0015
        device: cuda
        epochs: 800
        min_lr: 0
        warmup_epochs: 40
        weight_decay: 0.05
wandb:
    value:
        wandb: true
        wandb_entity: conradp-burton-gns-science
        wandb_project: Hephaestus-minicubes-MAE-pretrain
