[dataloader]

# random seed
seed = 42

# webdataset config
webdataset = true
webdataset_root = '/scratch/SDF25/Hephaestus_Minicubes_v0_webdataset/'
webdataset_write_processes = 4
webdataset_initial_buffer = 300
webdataset_shuffle_size = 100
num_workers = 4
max_samples_per_shard = 128
prefetch_factor = 2
persistent_workers = false

# insar specific
geomorphology_channels = ["insar_difference", "insar_coherence", "dem"]
atmospheric_channels =  ["total_column_water_vapour", "surface_pressure", "vertical_integral_of_temperature"]
timeseries_length = 1
timeseries_data = '../dataset/quality_timeseries_test.json'
train_years = ["20140101", "20190531"]
val_years = ["20190601", "20191231"]
test_years = ["20200101", "20211231"]
annotation_path = '../dataset/annotations_test.json'

# data specific
image_size = 512
zarr_path = '/scratch/SDF25/Hephaestus_Minicubes_v0/'
augment = false
mask_target = "union"
task = 'classification'
batch_size = 2


[model]

# model architecture
architecture = "ViT"

