[dataloader]
# random seed
seed = 42

# webdataset config
webdataset = true
webdataset_root = '/scratch/SDF25/Hephaestus_Minicubes_v0_webdataset/'
webdataset_write_processes = 4
webdataset_initial_buffer = 300
webdataset_shuffle_size = 100
num_workers = 4
max_samples_per_shard = 128
prefetch_factor = 2
persistent_workers = false

# insar specific
geomorphology_channels = ["insar_difference", "insar_coherence", "dem"]
atmospheric_channels =  ["total_column_water_vapour", "surface_pressure", "vertical_integral_of_temperature"]
timeseries = false
timeseries_length = 1
timeseries_data = '../dataset/quality_timeseries_test.json'
train_years = ["20140101", "20191231"] # pretraining extended into hephaestus publication val set end date (2019/12/31)
val_years = ["20200101", "20200531"] # unused
test_years = ["20200601", "20211231"] # unsued
annotation_path = '../dataset/annotations_test.json'

# data specific
augment = false
image_size = 512
zarr_path = '/scratch/SDF25/Hephaestus_Minicubes_v0/'
mask_target = "union"
task = 'classification'
batch_size = 32


[augmentations]
[augmentations.GaussianBlur]
value = [0.1, 2.0]
p = 0.3
[augmentations.RandomResizedCrop]
scale = [0.2, 1.0]
interpolation = 1
p = 0.3
[augmentations.HorizontalFlip]
p = 0.3
[augmentations.VerticalFlip]
p = 0.3
[augmentations.RandomRotation]
p = 0.6
[augmentations.ElasticTransform]
p = 0.0
[augmentations.Cutout]
p = 0.0
[augmentations.MultNoise]
p = 0.0
[augmentations.GaussianNoise]
p = 0.0


[model]
# ssl details
ssl_method = 'mae'
stage = 'pretraining' # one of pretraining, lin-probe, or finetuning

# model architecture
architecture = "ViT"
model = "mae_vit_base_patch16"

# other
norm_pix_loss = false
mask_ratio = 0.60


[train]
# training specific
device = 'cpu'
blr = 1.5e-4
min_lr = 0
weight_decay = 0.05
epochs = 40
warmup_epochs = 10


[wandb]
# weights and biases config
wandb = true
wandb_project = "Hephaestus-minicubes-MAE-pretrain"
wandb_entity = "conradp-burton-gns-science"


